resources:
  pipelines:
    nyc_pipeline:
      name: ${bundle.target}_nyc_taxi_pipeline
      catalog: ${var.target_catalog}
      # schema: ${var.schema}
      target: ${var.schema}
      serverless: true
      "libraries": [
        {
          "glob": {
            "include": "../src/dlt pipelines/**"
          }
        }
      ]
      configuration:
       target: ${bundle.target}
      #  raw_data_path: ${var.raw_data_path}
      "root_path": "../src/dlt pipelines"